---

- name: Preparing the base environment
  hosts: all

  tasks:
    - name: Ensure python additional modules for showoci are present | pandas, xlsxwriter
      pip:
        name:
          - pandas
          - xlsxwriter
        executable: pip3
...