---

- name: Preparing the base environment
  hosts: localhost

  tasks:
    - name: Ensure python dependencies are present | merge-CSV-to-Excel
      pip:
        name:
          - pandas
          - xlsxwriter
        executable: pip3

...