---

- name: Preparing the base environment
  hosts: localhost

  tasks:
    - name: Ensure python dependencies for merge-CSV-to-Excel are present | pandas, xlsxwriter
      pip:
        name:
          - pandas
          - xlsxwriter
        executable: pip3

...